"""Atualizando

Revision ID: 1c370b411f7c
Revises: f2a1e06991d6
Create Date: 2019-07-22 19:50:33.723182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c370b411f7c'
down_revision = 'f2a1e06991d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_cpf', table_name='model')
    op.create_index(op.f('ix_model_cpf'), 'model', ['cpf'], unique=False)
    op.drop_index('ix_model_nomecompleto', table_name='model')
    op.create_index(op.f('ix_model_nomecompleto'), 'model', ['nomecompleto'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_nomecompleto'), table_name='model')
    op.create_index('ix_model_nomecompleto', 'model', ['nomecompleto'], unique=1)
    op.drop_index(op.f('ix_model_cpf'), table_name='model')
    op.create_index('ix_model_cpf', 'model', ['cpf'], unique=1)
    # ### end Alembic commands ###
