"""Usando Models

Revision ID: f2a1e06991d6
Revises: 
Create Date: 2019-07-21 21:34:43.868860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a1e06991d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomecompleto', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.Integer(), nullable=True),
    sa.Column('sobrevoce', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_cidade'), 'model', ['cidade'], unique=False)
    op.create_index(op.f('ix_model_cpf'), 'model', ['cpf'], unique=True)
    op.create_index(op.f('ix_model_idade'), 'model', ['idade'], unique=False)
    op.create_index(op.f('ix_model_nomecompleto'), 'model', ['nomecompleto'], unique=True)
    op.create_index(op.f('ix_model_sobrevoce'), 'model', ['sobrevoce'], unique=False)
    op.create_index(op.f('ix_model_telefone'), 'model', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_telefone'), table_name='model')
    op.drop_index(op.f('ix_model_sobrevoce'), table_name='model')
    op.drop_index(op.f('ix_model_nomecompleto'), table_name='model')
    op.drop_index(op.f('ix_model_idade'), table_name='model')
    op.drop_index(op.f('ix_model_cpf'), table_name='model')
    op.drop_index(op.f('ix_model_cidade'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
